In [2]:
import pandas as pd
import numpy as np
import pickle

In [4]:
data = pd.read_csv('qsar_fish_toxicity.csv')
data.head()

CIC0  SM1_Dz(Z)  GATS1i  NdsCH  NdssC  MLOGP  LC50 [-LOG(mol/L)]
0  3.260      0.829   1.676    0.0      1  1.453               3.770
1  2.189      0.580   0.863    0.0      0  1.348               3.115
2  2.125      0.638   0.831    0.0      0  1.348               3.531
3  3.027      0.331   1.472    1.0      0  1.807               3.510
4  2.094      0.827   0.860    0.0      0  1.886               5.390

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 908 entries, 0 to 907
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   CIC0                906 non-null    float64
 1   SM1_Dz(Z)           906 non-null    float64
 2   GATS1i              906 non-null    float64
 3   NdsCH               907 non-null    float64
 4   NdssC               908 non-null    int64  
 5   MLOGP               905 non-null    float64
 6   LC50 [-LOG(mol/L)]  906 non-null    float64
dtypes: float64(6), int64(1)
memory usage: 49.8 KB


In [6]:
data['CIC0'].unique()

array([3.26 , 2.189, 2.125, 3.027, 2.094, 3.222, 3.179, 3.   , 2.62 ,
       2.834, 2.405, 2.728, 2.512, 2.819, 2.126, 3.014, 3.024, 3.036,
       2.707, 2.978, 3.111, 3.315, 2.71 , 3.326, 3.332, 3.896, 3.155,
       2.479, 1.075, 3.645, 3.079, 2.726, 3.532, 4.216, 3.605, 2.918,
       3.833, 3.669, 2.824, 2.233, 3.103, 4.413, 3.641, 3.073, 3.012,
       3.818, 4.171, 3.734, 2.216, 2.086, 3.08 , 1.636, 2.219, 1.594,
       1.818, 1.5  , 1.512, 2.56 , 1.359, 0.667, 2.333, 2.026, 0.965,
       1.951, 1.   , 3.219, 3.74 , 3.57 , 5.926, 3.802, 2.802, 2.242,
       1.94 , 3.277, 2.359, 2.565, 2.085, 2.26 , 2.91 , 2.866, 2.386,
       3.509, 2.98 , 3.462, 2.755, 2.024, 2.609, 2.878, 1.961, 2.665,
       1.251, 2.377, 2.366, 2.462, 1.778, 3.609, 3.316, 2.   , 3.441,
       2.429, 3.143, 2.709, 2.701, 3.252, 2.111, 3.361, 3.52 , 3.181,
       3.369, 2.507, 2.67 , 2.704, 3.566, 2.594, 3.485, 3.596, 3.199,
       2.57 , 4.005, 3.201, 3.98 , 4.114, 4.237, 4.63 , 2.456, 2.536,
       3.461, 2.641,

In [7]:
data['SM1_Dz(Z)'].unique()

array([0.829, 0.58 , 0.638, 0.331, 0.827, 0.   , 0.499, 0.134, 0.223,
       0.251, 0.56 , 0.452, 0.405, 0.972, 1.246, 0.732, 0.93 , 0.647,
       0.887, 1.161, 0.429, 0.496, 0.64 , 0.693, 0.977, 0.679, 0.83 ,
       0.582, 0.604, 0.486, 1.374, 1.096, 0.749, 1.079, 0.854, 0.811,
       1.028, 0.764, 1.16 , 1.834, 1.501, 0.956, 1.348, 0.88 , 1.586,
       1.318, 1.075, 0.711, 0.891, 1.408, 0.865, 0.934, 0.947, 0.923,
       1.47 , 1.211, 0.889, 1.286, 0.859, 0.872, 1.278, 1.07 , 1.821,
       1.38 , 1.292, 1.462, 1.437, 1.695, 1.331, 1.263, 0.357, 0.973,
       1.275, 2.044, 0.798, 1.182,   nan, 0.965, 1.232, 1.098, 0.713,
       1.153, 1.115, 1.593, 0.845, 1.772, 0.842, 1.336, 0.988, 1.192,
       1.317, 1.371, 1.327, 1.214, 0.918, 1.477, 0.702, 1.031, 0.907,
       2.171, 0.874, 1.421, 1.86 , 1.273, 1.621, 1.225, 0.949, 1.714,
       1.025, 1.03 , 1.306, 1.54 , 1.04 , 0.651, 1.496, 0.675, 1.236,
       1.718, 1.012, 0.762, 0.681, 1.131, 1.749, 0.57 , 1.3  , 1.548,
       0.389, 0.916,

In [8]:
data['GATS1i'].unique()

array([1.676, 0.863, 0.831, 1.472, 0.86 , 2.177, 1.063, 0.938, 0.99 ,
       0.95 , 0.843, 0.953, 0.929, 1.237, 1.271, 1.114, 1.322, 1.781,
       2.698, 1.205, 1.889, 1.103, 0.923, 0.96 , 0.724, 0.986, 1.294,
       1.984, 2.128, 0.954, 0.865, 1.155, 2.135, 1.519, 1.179, 1.11 ,
       1.248, 1.15 , 0.944, 1.522, 1.599, 1.   , 0.92 , 1.344, 1.17 ,
       1.933, 1.851, 1.023, 1.627, 1.678, 1.45 , 1.374, 0.771, 0.764,
       0.899, 0.839, 0.838, 0.917, 1.609, 1.695, 1.537, 1.333, 1.468,
       1.891, 1.844, 1.758, 1.445, 1.13 , 1.361, 1.946, 1.429, 1.068,
       1.878, 1.5  , 1.605, 1.581, 2.259, 1.671, 1.527, 1.6  , 1.907,
       1.066, 1.69 , 1.583, 1.869, 0.814, 1.987, 0.895, 0.836, 1.293,
       0.907, 1.385, 0.857, 1.478, 2.261, 1.959, 1.717, 1.559, 1.328,
       1.529, 1.684, 1.215, 1.762, 1.126, 2.111, 2.606, 2.102, 1.27 ,
       1.669, 1.203, 1.189, 1.571, 1.128, 1.667, 1.696, 1.641, 1.127,
       2.072, 2.003, 1.417, 1.253, 2.451, 1.437, 1.562, 1.52 , 1.614,
       1.633, 1.416,

In [12]:
data['NdsCH'].unique()

array([ 0.,  1.,  3.,  2.,  4., nan])

In [11]:
data['NdssC'].unique()

array([ 1,  0,  3,  2,  4, 20, -3,  5,  6], dtype=int64)

In [13]:
data.nunique()

CIC0                  502
SM1_Dz(Z)             186
GATS1i                556
NdsCH                   5
NdssC                   9
MLOGP                 559
LC50 [-LOG(mol/L)]    825
dtype: int64

In [14]:
data.isna().sum()

CIC0                  2
SM1_Dz(Z)             2
GATS1i                2
NdsCH                 1
NdssC                 0
MLOGP                 3
LC50 [-LOG(mol/L)]    2
dtype: int64

In [15]:
data['SM1_Dz(Z)'] = data['SM1_Dz(Z)'].replace(0,float('NaN'))

In [16]:
data.isna().sum()

CIC0                   2
SM1_Dz(Z)             38
GATS1i                 2
NdsCH                  1
NdssC                  0
MLOGP                  3
LC50 [-LOG(mol/L)]     2
dtype: int64

## Null Value removal

In [3]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5)

df_imputed = pd.DataFrame(imputer.fit_transform(data),columns=data.columns)
df_imputed['NdssC'] = df_imputed['NdssC'].astype(int)

print(df_imputed.isnull().sum())

data = df_imputed

NameError: name 'data' is not defined

## Outlier Removing

In [19]:
from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps=0.75, min_samples=3)
dbscan.fit(data)

# Get the cluster labels
labels = dbscan.labels_

outlier_indices = data[labels == -1].index

# Remove the outliers from the DataFrame
data = data.drop(outlier_indices)
print(len(data))

697


In [20]:
data.isna().sum()

CIC0                  0
SM1_Dz(Z)             0
GATS1i                0
NdsCH                 0
NdssC                 0
MLOGP                 0
LC50 [-LOG(mol/L)]    0
dtype: int64

In [21]:
data.to_csv('Cleaned_data.csv')

In [34]:
data.nunique()

CIC0                  372
SM1_Dz(Z)             158
GATS1i                426
NdsCH                   3
NdssC                   3
MLOGP                 411
LC50 [-LOG(mol/L)]    633
dtype: int64

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [37]:
X = data.drop('LC50 [-LOG(mol/L)]',axis=1)
y = data['LC50 [-LOG(mol/L)]']
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=49,test_size=0.2)

In [38]:
oh = OneHotEncoder()
oh.fit(X[['NdsCH','NdssC']])

OneHotEncoder()

In [39]:
colums_trans = make_column_transformer((OneHotEncoder(categories=oh.categories_),['NdsCH','NdssC']),
                                       remainder='passthrough')

In [40]:
lr = LinearRegression()

In [41]:
pipe = make_pipeline(colums_trans,lr)

In [42]:
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)

print(r2_score(y_test,y_pred))

0.7131010303091514


In [43]:
scores = []
for i in range(1000):
    X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=i,test_size=0.2)
    lr = LinearRegression()
    pipe = make_pipeline(colums_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    scores.append(r2_score(y_test,y_pred))
max_index = np.argmax(scores)
mx = scores[max_index]
print(mx)

0.8030131395845995


In [44]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=max_index,test_size=0.2)
lr = LinearRegression()
pipe = make_pipeline(colums_trans,lr)
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
r2_score(y_test,y_pred)

0.8030131395845995

In [45]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [46]:
pipe.predict(pd.DataFrame([[3,0.5,1.44,0,1,3.4]],columns=['CIC0','SM1_Dz(Z)','GATS1i','NdsCH','NdssC','MLOGP']))

array([4.25073242])